Add new component Regular Space
wildmeshing/wildmeshing-toolkit pull request #437
Opened 2023-10-11 20:21 UTC by Zhouyuan-Chen

2023-10-12 21:03 UTC, Zhouyuan-Chen commented
I wrote the basic operations, SplitFace, SplitFaceWithTag and SplitEdgeWithTag. I would rename the last two classes as SplitFaceWithTodoList and SplitEdgeWithTodoList.

2023-10-15 02:21 UTC, Zhouyuan-Chen commented
I found an interesting "bug" in the DEBUG_TriMesh. That is when you collapse an edge, it seems the maximum of the indices will not be modified. As a result, when you only have 4 vertices, you still have a vertex with idx = 4.

2023-10-16 00:01 UTC, Zhouyuan-Chen commented
I will first test the 1d case since the 2d case gets involved in the split result's direction. Something should be more clear about the result of the split operation in the document.

2023-10-16 22:45 UTC, daniel-zint commented
> I found an interesting "bug" in the DEBUG_TriMesh. That is when you collapse an edge, it seems the maximum of the indices will not be modified. As a result, when you only have 4 vertices, you still have a vertex with idx = 4.

This is not a bug. The mesh class does not yet have a garbage collection.

2023-10-16 23:28 UTC, daniel-zint requested changes
The approach is definitely good. The code requires quite some clean-up though.

2023-10-16 23:28 UTC, daniel-zint commented on src/wmtk/operations/tri_mesh/EdgeSplitWithTag.cpp
> +    m_pos_accessor.vector_attribute(m_output_tuple) = 0.5 * (p0 + p1);
You can make this a compound operation using `EdgeSplitAtMidpoint`.

2023-10-16 23:28 UTC, daniel-zint commented on src/wmtk/operations/tri_mesh/EdgeSplitWithTag.hpp
> +class EdgeSplitWithTag : public TriMeshOperation, private TupleOperation
Also here, please explain what this operation is doing. 
We have little to no documentation in our code and this is an issue we need to tackle.

2023-10-16 23:28 UTC, daniel-zint commented on src/wmtk/operations/tri_mesh/EdgeSplitWithTag.cpp
> +bool EdgeSplitWithTag::before() const
You don't need to override `before()`. It is already defined in the base class. Just remove `before` completely from your class.

2023-10-16 23:28 UTC, daniel-zint commented on src/wmtk/operations/tri_mesh/FaceSplit.hpp
> +    Tuple return_tuple() const;
Very well documented, just change the format to doxygen style:
```
/**
* The return tuple is the new vertex, pointing to the original vertex.
* This operation does not set vertex positions.  <-- this belongs to the explanation of the class
* 
*           / | \
*          /  |  \
*        /  _*_  \
*      / _< f \_ \
*      |/_______\|
*       \          /
*         \      /
*           \  /
*/
```
Something like that. Sorry, I messed up the image 😅

2023-10-16 23:28 UTC, daniel-zint commented on src/wmtk/operations/tri_mesh/FaceSplitWithTag.hpp
> +    Eigen::Vector3d p0;
Please do not use the class as a "local storage". These variables should be defined in `execute`.

2023-10-16 23:28 UTC, daniel-zint commented on src/wmtk/operations/tri_mesh/FaceSplitWithTag.cpp
> +    m_pos_accessor.vector_attribute(m_output_tuple) = (p0 + p1 + p2) / 3.0;
Just like for the `EdgeSplitWithTag` it would be cleaner if you would have a `FaceSplitAtMidpoint` operation that you call here.

2023-10-16 23:28 UTC, daniel-zint commented on tests/components/test_component_regular_space.cpp
> +TriMesh hex_plus_two()
This examples exist in `tools/TriMesh_examples.hpp`. Use those.

2023-10-16 23:28 UTC, daniel-zint commented on tests/components/test_component_regular_space.cpp
> +TEST_CASE("file reading", "[components][regular_space][.]")
Test cases must not use space. `file reading` --> `file_reading`.
Furthermore, be more specific with the test case name. The test cases have to have unique names across all tests.

2023-10-16 23:28 UTC, daniel-zint commented on tests/components/test_component_regular_space.cpp
> +        {"split_tag_value"}};
This component does not do anything for now and I assume it should do more in the future.

Add a TODO comment, explaining what needs to be done and add a `REQUIRE(false)`.

2023-10-16 23:28 UTC, daniel-zint commented on tests/components/test_component_regular_space.cpp
> +    long input_value = 1;
`const`

2023-10-16 23:28 UTC, daniel-zint commented on tests/components/test_component_regular_space.cpp
> +        m.get_attribute_handle<double>(std::string("position"), wmtk::PrimitiveType::Vertex);
`"position"` is sufficient. There is no need for `std::string( )`.

2023-10-16 23:28 UTC, daniel-zint commented on tests/components/test_component_regular_space.cpp
> +    ParaviewWriter writer1(data_dir / "my_result", "position", m, true, true, true, false);
Despite the current issue with the `ParaviewWriter`, you can (and should) run checks here. You know what result you expect so iterate through the mesh and make sure that all attributes are as expected.

2023-10-16 23:28 UTC, daniel-zint commented on tests/test_2d_operations.cpp
> +        REQUIRE(m.get_all(PV).size() == 4);
Everything from this line on should be `CHECK`s not `REQUIRE`s.

2023-10-16 23:28 UTC, daniel-zint commented on tests/test_2d_operations.cpp
> +        spdlog::info("{} {}", m.id(ret, PV), m.id(m.switch_vertex(ret), PV));
I guess that is still debug code but `CHECK`s are missing and the tests should not contain any debug messages, if not necessary.

2023-10-17 14:45 UTC, Zhouyuan-Chen commented on components/wmtk_components/regular_space/internal/RegularSpace.hpp
> +    long m_split_tag_value;
when you split a simplicity, you will set m_split_tag_value to the new simplicity

2023-10-17 20:18 UTC, Zhouyuan-Chen commented
I still need to add the last few tests. Will be done soon.

2023-10-18 23:03 UTC, Zhouyuan-Chen commented
This component is done, wait to be reviewed

2023-10-23 14:10 UTC, Zhouyuan-Chen commented
I modified the code, but some codes I can't cover by tests, seems those codes are impossible to execute😅. however, for the safety of the code, those code is needed.

2023-10-23 23:06 UTC, daniel-zint approved these changes
Lgtm. Just resolve my comments from the previous review.

2023-10-24 18:26 UTC, Zhouyuan-Chen commented
Just remove the variable never used in the test file

2023-10-26 00:15 UTC, daniel-zint approved these changes
Good for now. It's ready to be merged.

2023-10-26 00:16 UTC, merged