Zhouyuan/edge mesh input
wildmeshing/wildmeshing-toolkit pull request #448
Opened 2023-10-13 20:04 UTC by Zhouyuan-Chen

Reopen the edge mesh input. I closed this PR since I changed the name recently.

This part's EdgeMesh is outdated and need to update that part code.

2023-10-13 20:27 UTC, daniel-zint requested changes
The new classes requires testing. I assume the code works but we need unit tests to prove it.

2023-10-13 20:27 UTC, daniel-zint commented on src/wmtk/io/EdgeMeshReader.hpp
> +public:
Make sure that only those functions are `public` that need to be. The rest should be `private`.

2023-10-13 20:27 UTC, daniel-zint commented on src/wmtk/io/EdgeMeshReader.hpp
> +    void read(
All these functions need to covered in tests.

2023-10-13 20:27 UTC, daniel-zint commented on components/wmtk_components/input/input.cpp
> +        spdlog::warn("this edge mesh is old version, need to update according to the latest "
Now as you have the `EdgeMesh` available, you should remove the warning and adapt the code.

2023-10-16 14:52 UTC, Zhouyuan-Chen commented
Added the tests.
Edge Mesh Input finished.

2023-10-16 19:14 UTC, daniel-zint commented
Whenever you add the tag `[.]` to a test, it is ignored. You need to remove them.

2023-10-16 22:41 UTC, daniel-zint requested changes
I'll review it once the tests are running in the CLI.

You can upload your OBJ file for testing here:
https://github.com/wildmeshing/data

2023-11-06 18:07 UTC, Zhouyuan-Chen commented
This component will not be used anymore, I will delete this branch later.

2023-11-06 20:00 UTC, closed without merging