extract child mesh from tag for trimesh
wildmeshing/wildmeshing-toolkit pull request #502
Opened 2023-11-08 09:33 UTC by JcDai

2023-11-08 21:18 UTC, JcDai reviewed
need to check if the current implementation of filling the child mesh matrix preserve the orientation for all possible cases.

2023-11-09 22:41 UTC, mtao requested changes
mostly there. just deal with my comments

2023-11-09 22:41 UTC, mtao commented on src/wmtk/Mesh.hpp
> +        const PrimitiveType& pt);
this pt is redundant with tag_handle.primitive_type() isn't it?

2023-11-09 22:41 UTC, mtao commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +            const long v1 = m.id(tagged_tuples[i], PrimitiveType::Vertex);
make this a `const std::array<long,2>`. this allows for line 55 and 59 to turn into a for loop, same with 65/66.

2023-11-09 22:41 UTC, mtao commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +            // TODO: check if this break the orientation of the map
same as before about using an array

2023-11-09 22:41 UTC, mtao commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +            if (parent_to_child_vertex_map.find(v1) == parent_to_child_vertex_map.end()) {
there's a pattern like
```
size_t size = parent_to_Child_Vertex_map.size();
parent_to_child_vertex_map.try_emplace(v,size);
```
that is a little easier to read i think

2023-11-09 22:41 UTC, mtao commented on src/wmtk/Mesh.hpp
> +        Mesh& m,
this done doesn't need to be a friend

2023-11-10 23:25 UTC, mtao approved these changes
lgtm

2023-11-14 19:18 UTC, daniel-zint approved these changes
The functionality is there. Just clean it up and you're good to go.

Please be a more careful about when to use which integer data type. `int`,`long`, and `size_t` are not the same thing.

2023-11-14 19:18 UTC, daniel-zint commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.hpp
> +    const PrimitiveType& pt);
`PrimitiveType` should not be passed by reference. Just pass it by value.

2023-11-14 19:18 UTC, daniel-zint commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +    PrimitiveType pt = tag_handle.primitive_type();
`const`

2023-11-14 19:18 UTC, daniel-zint commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +    for (auto t : m.get_all(pt)) {
`const Tuple& t`

2023-11-14 19:18 UTC, daniel-zint commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +    case PrimitiveType::Vertex: throw("not implemented");
You can add a simple test case for that using `CHECK_THROWS()`. This test case can then later be modified when there is something actually happening.

2023-11-14 19:18 UTC, daniel-zint commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +        for (long i = 0; i < tagged_tuples.size(); ++i) {
should be `size_t`

2023-11-14 19:18 UTC, daniel-zint commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +            for (int k = 0; k < 2; k++) {
`size_t`

2023-11-14 19:18 UTC, daniel-zint commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +        auto edgemesh_edge_tuples = child.get_all(PrimitiveType::Edge);
`const`

2023-11-14 19:18 UTC, daniel-zint commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +        for (long i = 0; i < tagged_tuples.size(); ++i) {
`size_t`

2023-11-14 19:18 UTC, daniel-zint commented on src/wmtk/multimesh/utils/extract_child_mesh_from_tag.cpp
> +    case PrimitiveType::Face: {
Just looking at what Codecov reports, it seems like you did not test that part of the code. Please add a test.

2023-11-14 19:18 UTC, daniel-zint commented on tests/test_extract_child_mesh.cpp
> +namespace {} // namespace
?

2023-11-14 19:18 UTC, daniel-zint commented on tests/test_extract_child_mesh.cpp
> +    std::declval<Accessor<long>&>()));
If I see it correctly, you are neither using `TM` nor `TMOE`. Please remove that.

2023-11-14 19:18 UTC, daniel-zint commented on tests/test_extract_child_mesh.cpp
> +        for (auto t : parent.get_all(PE)) {
`const Tuple& t`

2023-11-14 19:18 UTC, daniel-zint commented on tests/test_extract_child_mesh.cpp
> +        REQUIRE(child0.get_all(PE).size() == 3);
should be `CHECK`s

2023-11-14 19:18 UTC, daniel-zint commented on tests/test_extract_child_mesh.cpp
> +//     auto& child0 = *child0_ptr;
What's with all that commented out code? Where does it come from and why is it here?

2023-11-15 00:09 UTC, daniel-zint approved these changes
lgtm

2023-11-15 04:54 UTC, merged